# NumPy: the absolute basics for beginners

## 1. NumPy 가져오기(How to import NumPy)

In [5]:
import numpy as np

In [6]:
## 2. 예제 코드 읽기(Reading the example code)

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

## 2. 배열 기초 (Array Fundamentals)

In [8]:
# 리스트로 1D 배열 생성
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
# 인덱스로 요소 접근 (0-indexed)
a[0]

np.int32(1)

In [10]:
# 배열은 변경 가능(mutable)
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [11]:
# 슬라이싱
a[:3]

array([10,  2,  3])

In [12]:
# 슬라이스는 뷰(view)를 반환 — 원본 배열을 수정함
b = a[3:]
print('b:', b)
b[0] = 40
print('a after modifying b:', a)

b: [4 5 6]
a after modifying b: [10  2  3 40  5  6]


In [13]:
# 중첩 리스트로 2D 배열 생성
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# 2D 배열 요소 접근: [행, 열]
a[1, 3]

np.int32(8)

## 3. 배열 속성 (Array Attributes)

`ndim`, `shape`, `size`, `dtype`

In [15]:
# 차원 수
a.ndim

2

In [16]:
# 모양 (shape)
print(a.shape)
print(len(a.shape) == a.ndim)

(3, 4)
True


In [17]:
# 전체 요소 수
import math
print(a.size)
print(a.size == math.prod(a.shape))

12
True


In [18]:
# 데이터 타입
a.dtype

dtype('int32')

## 4. 기본 배열 생성 (How to Create a Basic Array)

`np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

In [19]:
# 0으로 채워진 배열
np.zeros(2)

array([0., 0.])

In [20]:
# 1로 채워진 배열
np.ones(2)

array([1., 1.])

In [21]:
# 초기화되지 않은 배열 (빠르지만 값이 임의적)
np.empty(2)  # 값은 매번 다를 수 있음

array([1., 1.])

In [22]:
# 범위 배열
np.arange(4)

array([0, 1, 2, 3])

In [23]:
# 시작, 끝, 간격 지정
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [24]:
# 균등 간격 배열
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
# dtype 지정
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

## 5. 요소 추가, 제거, 정렬 (Adding, Removing, and Sorting Elements)

`np.sort()`, `np.concatenate()`

In [26]:
# 정렬
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
# 1D 배열 연결
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# 2D 배열 연결 (axis=0: 행 방향)
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 6. 배열의 모양과 크기 (Shape and Size)

`ndarray.ndim`, `ndarray.size`, `ndarray.shape`

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])

print('ndim:', array_example.ndim)
print('size:', array_example.size)
print('shape:', array_example.shape)

ndim: 3
size: 24
shape: (3, 2, 4)


## 7. 배열 재구성 (Reshape)

`arr.reshape()`

In [30]:
a = np.arange(6)
print('원본:', a)

b = a.reshape(3, 2)
print('reshape(3, 2):')
print(b)

원본: [0 1 2 3 4 5]
reshape(3, 2):
[[0 1]
 [2 3]
 [4 5]]


In [31]:
# np.reshape에 선택적 파라미터 사용
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## 8. 새로운 축 추가 (1D → 2D)

`np.newaxis`, `np.expand_dims`

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
print('원본 shape:', a.shape)

# newaxis로 행 벡터(row vector) 생성
row_vector = a[np.newaxis, :]
print('row_vector shape:', row_vector.shape)

# newaxis로 열 벡터(column vector) 생성
col_vector = a[:, np.newaxis]
print('col_vector shape:', col_vector.shape)

원본 shape: (6,)
row_vector shape: (1, 6)
col_vector shape: (6, 1)


In [33]:
# expand_dims 사용
b = np.expand_dims(a, axis=1)
print('expand_dims(axis=1) shape:', b.shape)

c = np.expand_dims(a, axis=0)
print('expand_dims(axis=0) shape:', c.shape)

expand_dims(axis=1) shape: (6, 1)
expand_dims(axis=0) shape: (1, 6)


## 9. 인덱싱과 슬라이싱 (Indexing and Slicing)

In [34]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [35]:
# 조건을 이용한 요소 선택
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('5보다 작은 값:', a[a < 5])
print('5 이상인 값:', a[a >= 5])
print('2로 나누어지는 값:', a[a % 2 == 0])

5보다 작은 값: [1 2 3 4]
5 이상인 값: [ 5  6  7  8  9 10 11 12]
2로 나누어지는 값: [ 2  4  6  8 10 12]


In [36]:
# & 와 | 연산자로 복합 조건
c = a[(a > 2) & (a < 11)]
print('2 초과 11 미만:', c)

five_up = (a > 5) | (a == 5)
print('5 이상인지 boolean:')
print(five_up)

2 초과 11 미만: [ 3  4  5  6  7  8  9 10]
5 이상인지 boolean:
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [37]:
# np.nonzero() 사용
b = np.nonzero(a < 5)
print('5보다 작은 요소의 인덱스:', b)

list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print('해당 요소들:', a[b])

# 존재하지 않는 요소 검색
not_there = np.nonzero(a == 42)
print('없는 요소:', not_there)

5보다 작은 요소의 인덱스: (array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(np.int32(0), np.int32(0))
(np.int32(0), np.int32(1))
(np.int32(0), np.int32(2))
(np.int32(0), np.int32(3))
해당 요소들: [1 2 3 4]
없는 요소: (array([], dtype=int32), array([], dtype=int32))


## 10. 기존 데이터로 배열 생성 (Create Array from Existing Data)

`slicing`, `np.vstack()`, `np.hstack()`, `np.hsplit()`, `.view()`, `.copy()`

In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 슬라이싱으로 새 배열 생성
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [39]:
# vstack (수직 스택)
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

print('vstack:')
print(np.vstack((a1, a2)))

vstack:
[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [40]:
# hstack (수평 스택)
print('hstack:')
print(np.hstack((a1, a2)))

hstack:
[[1 1 3 3]
 [2 2 4 4]]


In [41]:
# hsplit (수평 분할)
x = np.arange(1, 25).reshape(2, 12)
print('원본:')
print(x)

print('\n3등분:')
print(np.hsplit(x, 3))

print('\n3번째, 4번째 열 이후 분할:')
print(np.hsplit(x, (3, 4)))

원본:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

3등분:
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]

3번째, 4번째 열 이후 분할:
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [42]:
# view (얕은 복사): 원본 수정됨
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
print('b1:', b1)
b1[0] = 99
print('b1 수정 후 b1:', b1)
print('b1 수정 후 a:')
print(a)

b1: [1 2 3 4]
b1 수정 후 b1: [99  2  3  4]
b1 수정 후 a:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# copy (깊은 복사): 원본 유지됨
b2 = a.copy()
b2[0, 0] = 0
print('b2 수정 후 a (원본 유지):')
print(a)

b2 수정 후 a (원본 유지):
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 11. 기본 배열 연산 (Basic Array Operations)

In [44]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print('더하기:', data + ones)
print('빼기:', data - ones)
print('곱하기:', data * data)
print('나누기:', data / data)

더하기: [2 3]
빼기: [0 1]
곱하기: [1 4]
나누기: [1. 1.]


In [45]:
# 합계
a = np.array([1, 2, 3, 4])
print('sum:', a.sum())

# 2D 배열에서 축(axis) 기준 합계
b = np.array([[1, 1], [2, 2]])
print('axis=0 합계 (열 방향):', b.sum(axis=0))
print('axis=1 합계 (행 방향):', b.sum(axis=1))

sum: 10
axis=0 합계 (열 방향): [3 3]
axis=1 합계 (행 방향): [2 4]


## 12. 브로드캐스팅 (Broadcasting)

In [46]:
# 스칼라 연산 (마일 → 킬로미터)
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

## 13. 유용한 집계 함수 (More Useful Array Operations)

`max`, `min`, `sum`, `mean`, `prod`, `std`

In [47]:
data = np.array([1, 2, 3])
print('max:', data.max())
print('min:', data.min())
print('sum:', data.sum())

max: 3
min: 1
sum: 6


In [48]:
# axis 기준 최솟값
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print('전체 합계:', a.sum())
print('전체 최솟값:', a.min())
print('각 열의 최솟값 (axis=0):', a.min(axis=0))

전체 합계: 4.8595784
전체 최솟값: 0.05093587
각 열의 최솟값 (axis=0): [0.12697628 0.05093587 0.26590556 0.5510652 ]


## 14. 행렬 생성 (Creating Matrices)

In [49]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

# 인덱싱과 슬라이싱
print('data[0, 1]:', data[0, 1])
print('data[1:3]:')
print(data[1:3])
print('data[0:2, 0]:', data[0:2, 0])

[[1 2]
 [3 4]
 [5 6]]
data[0, 1]: 2
data[1:3]:
[[3 4]
 [5 6]]
data[0:2, 0]: [1 3]


In [50]:
# 행렬 집계
print('max:', data.max())
print('min:', data.min())
print('sum:', data.sum())

max: 6
min: 1
sum: 21


In [51]:
# axis 기준 최댓값
data = np.array([[1, 2], [5, 3], [4, 6]])
print('axis=0 최댓값:', data.max(axis=0))
print('axis=1 최댓값:', data.max(axis=1))

axis=0 최댓값: [5 6]
axis=1 최댓값: [2 5 6]


In [52]:
# 행렬 산술 연산
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print('data + ones:')
print(data + ones)

data + ones:
[[2 3]
 [4 5]]


In [53]:
# 브로드캐스팅을 활용한 행렬 연산
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print('data + ones_row (브로드캐스팅):')
print(data + ones_row)

data + ones_row (브로드캐스팅):
[[2 3]
 [4 5]
 [6 7]]


In [54]:
# N차원 배열 출력 예시
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [55]:
# ones, zeros, random으로 2D 배열 생성
rng = np.random.default_rng()

print('ones(3, 2):')
print(np.ones((3, 2)))
print('zeros(3, 2):')
print(np.zeros((3, 2)))
print('random(3, 2):')
print(rng.random((3, 2)))

ones(3, 2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]
zeros(3, 2):
[[0. 0.]
 [0. 0.]
 [0. 0.]]
random(3, 2):
[[0.37843242 0.7216397 ]
 [0.38692566 0.41489864]
 [0.62051351 0.93555571]]


## 15. 난수 생성 (Generating Random Numbers)

In [57]:
rng = np.random.default_rng()

# 0~4 사이의 정수 난수 2x4 배열 생성
rng.integers(5, size=(2, 4))

array([[2, 4, 2, 0],
       [2, 2, 3, 0]], dtype=int64)

## 16. 고유 값 및 개수 (Unique Items and Counts)

`np.unique()`

In [58]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

# 고유 값
unique_values = np.unique(a)
print('고유 값:', unique_values)

고유 값: [11 12 13 14 15 16 17 18 19 20]


In [59]:
# 고유 값의 첫 번째 인덱스
unique_values, indices_list = np.unique(a, return_index=True)
print('첫 번째 인덱스:', indices_list)

첫 번째 인덱스: [ 0  2  3  4  5  6  7 12 13 14]


In [60]:
# 고유 값의 등장 횟수
unique_values, occurrence_count = np.unique(a, return_counts=True)
print('등장 횟수:', occurrence_count)

등장 횟수: [3 2 2 2 1 1 1 1 1 1]


In [61]:
# 2D 배열에서 고유 행 찾기
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)

print('고유 행:')
print(unique_rows)
print('인덱스:', indices)
print('등장 횟수:', occurrence_count)

고유 행:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
인덱스: [0 1 2]
등장 횟수: [2 1 1]


## 17. 행렬 전치와 재구성 (Transposing and Reshaping a Matrix)

`arr.reshape()`, `arr.transpose()`, `arr.T`

In [62]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print('reshape(2, 3):')
print(data.reshape(2, 3))
print('reshape(3, 2):')
print(data.reshape(3, 2))

reshape(2, 3):
[[1 2 3]
 [4 5 6]]
reshape(3, 2):
[[1 2]
 [3 4]
 [5 6]]


In [63]:
# transpose 사용
arr = np.arange(6).reshape((2, 3))
print('원본:')
print(arr)
print('transpose():')
print(arr.transpose())
print('.T:')
print(arr.T)

원본:
[[0 1 2]
 [3 4 5]]
transpose():
[[0 3]
 [1 4]
 [2 5]]
.T:
[[0 3]
 [1 4]
 [2 5]]


## 18. 배열 뒤집기 (How to Reverse an Array)

`np.flip()`

In [64]:
# 1D 배열 뒤집기
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('뒤집힌 배열:', reversed_arr)

뒤집힌 배열: [8 7 6 5 4 3 2 1]


In [65]:
# 2D 배열 뒤집기
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('전체 뒤집기:')
print(np.flip(arr_2d))

print('행 방향 뒤집기 (axis=0):')
print(np.flip(arr_2d, axis=0))

print('열 방향 뒤집기 (axis=1):')
print(np.flip(arr_2d, axis=1))

전체 뒤집기:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
행 방향 뒤집기 (axis=0):
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
열 방향 뒤집기 (axis=1):
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [66]:
# 특정 행/열만 뒤집기
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr_2d[1] = np.flip(arr_2d[1])  # 두 번째 행 뒤집기
print('두 번째 행 뒤집기:')
print(arr_2d)

arr_2d[:, 1] = np.flip(arr_2d[:, 1])  # 두 번째 열 뒤집기
print('두 번째 열 뒤집기:')
print(arr_2d)

두 번째 행 뒤집기:
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
두 번째 열 뒤집기:
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## 19. 다차원 배열 재구성 및 평탄화 (Reshaping and Flattening Multidimensional Arrays)

`.flatten()`, `.ravel()`

In [67]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# flatten: 깊은 복사 (원본에 영향 없음)
print('flatten 결과:', x.flatten())

flatten 결과: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
# flatten은 원본을 수정하지 않음
a1 = x.flatten()
a1[0] = 99
print('원본 x (변경 없음):')
print(x)
print('a1 (변경됨):', a1)

원본 x (변경 없음):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a1 (변경됨): [99  2  3  4  5  6  7  8  9 10 11 12]


In [69]:
# ravel: 얕은 복사 (원본도 수정됨)
a2 = x.ravel()
a2[0] = 98
print('원본 x (변경됨!):')
print(x)
print('a2:', a2)

원본 x (변경됨!):
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a2: [98  2  3  4  5  6  7  8  9 10 11 12]
